# Generated by Django 4.2.30 on 2026-05-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScrapeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(max_length=50)),
                ("keyword", models.CharField(max_length=255)),
                ("limit", models.IntegerField()),
                ("results_count", models.IntegerField(default=0)),
                ("sentiment_summary", models.JSONField(blank=True, null=True)),
                ("raw_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "scrape_histories",
                "ordering": ["-created_at"],
            },
        ),
    ]
