# Generated by Django 4.2.30 on 2026-06-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PopularSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "keyword",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("count", models.IntegerField(default=1)),
                ("last_searched", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "popular_searches",
                "ordering": ["-count", "-last_searched"],
            },
        ),
    ]
