# Generated by Django 4.2.30 on 2026-06-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0002_popularsearch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scrapehistory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="scrapehistory",
            name="keyword",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="scrapehistory",
            name="platform",
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
