# Generated by Django 4.2.30 on 2026-08-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0003_alter_scrapehistory_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeywordTrend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(db_index=True, max_length=255)),
                ("positive", models.IntegerField(default=0)),
                ("negative", models.IntegerField(default=0)),
                ("neutral", models.IntegerField(default=0)),
                ("total", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "keyword_trends",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["keyword", "created_at"], name="trend_keyword_date_idx"
                    )
                ],
            },
        ),
    ]
